"""
Tool schemas for QuickBin MCP server

Defines the schemas for tools and resources provided by the QuickBin MCP server.
"""

from typing import Dict, Any, List


def get_tool_schemas() -> List[Dict[str, Any]]:
    """Get tool schemas for QuickBin MCP server"""
    return [
        {
            "name": "bin_contigs",
            "description": "Bin contigs using coverage and kmer frequencies with QuickBin",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "contigs_path": {
                        "type": "string",
                        "description": "Path to assembled contigs file (FASTA format)"
                    },
                    "sam_files": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of SAM/BAM alignment files for coverage calculation"
                    },
                    "output_pattern": {
                        "type": "string",
                        "description": "Output pattern for bins (e.g., 'bin%.fa' or 'bins/')"
                    },
                    "stringency": {
                        "type": "string",
                        "enum": ["xstrict", "strict", "normal", "loose", "xloose"],
                        "default": "normal",
                        "description": "Binning stringency level"
                    },
                    "additional_params": {
                        "type": "string",
                        "description": "Additional QuickBin parameters (optional)"
                    }
                },
                "required": ["contigs_path", "sam_files", "output_pattern"]
            }
        },
        {
            "name": "bin_contigs_with_coverage",
            "description": "Bin contigs using pre-calculated coverage file",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "contigs_path": {
                        "type": "string",
                        "description": "Path to assembled contigs file (FASTA format)"
                    },
                    "coverage_file": {
                        "type": "string",
                        "description": "Path to coverage file generated by QuickBin or similar tool"
                    },
                    "output_pattern": {
                        "type": "string",
                        "description": "Output pattern for bins (e.g., 'bin%.fa' or 'bins/')"
                    },
                    "stringency": {
                        "type": "string",
                        "enum": ["xstrict", "strict", "normal", "loose", "xloose"],
                        "default": "normal",
                        "description": "Binning stringency level"
                    },
                    "additional_params": {
                        "type": "string",
                        "description": "Additional QuickBin parameters (optional)"
                    }
                },
                "required": ["contigs_path", "coverage_file", "output_pattern"]
            }
        },
        {
            "name": "generate_coverage",
            "description": "Generate coverage statistics from SAM files for later binning",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "contigs_path": {
                        "type": "string",
                        "description": "Path to assembled contigs file (FASTA format)"
                    },
                    "sam_files": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of SAM/BAM alignment files"
                    },
                    "output_coverage": {
                        "type": "string",
                        "description": "Output path for coverage file"
                    },
                    "additional_params": {
                        "type": "string",
                        "description": "Additional parameters for coverage calculation"
                    }
                },
                "required": ["contigs_path", "sam_files", "output_coverage"]
            }
        },
        {
            "name": "evaluate_bins",
            "description": "Evaluate binning quality and completeness",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "bin_directory": {
                        "type": "string",
                        "description": "Directory containing binned contigs"
                    },
                    "reference_taxonomy": {
                        "type": "string",
                        "description": "Optional reference taxonomy for validation"
                    },
                    "additional_params": {
                        "type": "string",
                        "description": "Additional evaluation parameters"
                    }
                },
                "required": ["bin_directory"]
            }
        }
    ]


def get_resource_schemas() -> List[Dict[str, Any]]:
    """Get resource schemas for QuickBin MCP server"""
    return [
        {
            "uri": "quickbin://docs/user-guide",
            "name": "QuickBin User Guide",
            "description": "Comprehensive guide for using QuickBin tools",
            "mimeType": "text/markdown"
        },
        {
            "uri": "quickbin://examples/metagenome-workflow",
            "name": "Metagenome Binning Workflow",
            "description": "Complete workflow example for metagenome binning",
            "mimeType": "text/markdown"
        },
        {
            "uri": "quickbin://tools/available",
            "name": "Available QuickBin Tools",
            "description": "List of available tools and their descriptions",
            "mimeType": "application/json"
        },
        {
            "uri": "quickbin://parameters/stringency",
            "name": "Stringency Parameter Guide",
            "description": "Detailed guide for choosing stringency parameters",
            "mimeType": "text/markdown"
        }
    ]
