[project]
name = "biocoding-mcp"
version = "0.1.0"
description = "BioCoding MCP Server - Interactive code creation, execution, and analysis for biological data science"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.9,<3.12"
pip = "*"

# Scientific computing and ML dependencies
numpy = ">=1.26.0"
pandas = ">=2.0.0"
matplotlib = ">=3.7.0"
seaborn = ">=0.12.0"
scikit-learn = ">=1.3.0"
scipy = ">=1.11.0"
biopython = ">=1.83"

# Code analysis and formatting
black = ">=23.0.0"
autopep8 = ">=2.0.0"

# Visualization and reporting
plotly = ">=5.18.0"
wordcloud = ">=1.9.0"

# Core dependencies for MCP
pydantic = ">=2.7.0"

[pypi-dependencies]
mcp = ">=0.1.0"
fastmcp = ">=1.0"
nbformat = ">=5.9.0"
tabulate = ">=0.9.0"

[tasks]
# Server tasks
run = "python -m src.server"
test = "python test_simplified.py"
test-full = "pytest tests/ -v"

# Development
format = "black src/ tests/ && ruff check --fix src/ tests/"
lint = "black --check src/ tests/ && ruff check src/ tests/"

[environments]
default = { solve-group = "default" }